import os
import glob

configfile: "config_dev.yaml"

# Get the raw_dir from the config
fastq_dir = config["raw_dir"]

# Function to get sample IDs based on the presence of fastq files in subdirectories
def get_sample_ids():
    sample_ids = []
    # Iterate over directories in the fastq directory
    for subdir in os.listdir(fastq_dir):
        subdir_path = os.path.join(fastq_dir, subdir)
        if os.path.isdir(subdir_path):
            # Check for FASTQ files in the subdirectory
            fastq_files = glob.glob(os.path.join(subdir_path, "*.fastq.gz"))
            if fastq_files:
                # Add the directory name as the sample ID
                sample_ids.append(subdir)
                print(subdir)
    return sample_ids

sample_ids = get_sample_ids()

# Print debug information
print("fastq_dir:", fastq_dir)
print("sample_ids:", sample_ids)

rule all:
    input:
        expand(os.path.join(config["results_dir"], "{sample}_junctions.bed"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_barcodes.txt"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed"), sample=sample_ids)

# Rule to generate STAR index
rule generate_star_index:
    output:
        directory(config["star_index_dir"]),
        flag = touch(config["star_index_dir"] + "/index_complete.flag")
    params:
        genome_fasta = config["genome_fasta"],
        gtf_file = config["gtf_file"]
    shell:
        """
        star --runThreadN 4 \
             --runMode genomeGenerate \
             --genomeDir {output[0]} \
             --genomeFastaFiles {params.genome_fasta} \
             --sjdbGTFfile {params.gtf_file}
        """

rule run_star:
    input:
        fastq1=os.path.join(config["raw_dir"], "{sample}", "{sample}_1.fastq.gz"),
        fastq2=os.path.join(config["raw_dir"], "{sample}", "{sample}_2.fastq.gz"),
        index=config["star_index_dir"] + "/index_complete.flag"
    output:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam"),
    params:
        star_index_dir=config['star_index_dir'],
        output_prefix=os.path.join(config["bam_files"], "{sample}/")
    shell:
        """
        star --genomeDir {params.star_index_dir} \
             --readFilesIn {input.fastq1} {input.fastq2} \
             --readFilesCommand zcat \
             --runMode alignReads \
             --outSAMattributes XS \
             --outSAMstrandField intronMotif \
             --limitBAMsortRAM 44006670219 \
             --outSAMtype BAM SortedByCoordinate \
             --runThreadN 4 \
             --twopassMode Basic \
             --outFileNamePrefix {params.output_prefix}
        """

rule add_cb_tag:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam")
    output:
        bam_CB=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam")
    params:
        sample=lambda wildcards: wildcards.sample
    shell:
        """
        echo "Adding CB tag to BAM file: {input.bam}"
        samtools view -h {input.bam} | awk -v cb={params.sample} 'BEGIN {{OFS="\t"}} {{$NF = $NF"\tCB:Z:"cb; print}}' | samtools view -bS - > {output.bam_CB}
        """

# Rule to index BAM file
rule index_bam:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam")
    output:
        bai=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam.bai")
    shell:
        """
        echo "Indexing BAM file: {input.bam}"
        samtools index {input.bam}
        """

rule extract_junctions:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam"),
        bai=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam.bai")
    output:
        juncs=os.path.join(config["results_dir"], "{sample}_junctions.bed"),
        barcodes=os.path.join(config["results_dir"], "{sample}_barcodes.txt"),
        juncswbarcodes=os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed")
    params:
        regtools_path=config["regtools_path"]
    shell:
        """
        echo "Extracting junctions with barcodes from BAM file: {input.bam}"
        {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} -o {output.juncs} -s XS -b {output.barcodes}
        paste --delimiters='\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}
        echo "Done extracting junctions with barcodes"
        """