import pandas as pd
import numpy as np

# Function to print a separator line
def print_separator():
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

# define function to read individual featureCounts files, clean up column names 
def get_featureCounts(file_name):

    """
    This function reads in a featureCounts file and returns a dataframe with cleaned up column names
    Input: file_name, full path for output generated by featureCounts (string)
    Output: df, dataframe with cleaned up column names (dataframe)
    """

    df = pd.read_csv(file_name, sep='\t', skiprows=1, index_col=0, low_memory = False)
    cell_type = file_name.split('/')[-1].split('_')
    # combine first three elements 
    cell_type = '_'.join(cell_type[0:3])
    df = df.iloc[:,5:]
    df = df.iloc[:,5:]
    df.columns = [x.split('/')[1] for x in df.columns]
    df.columns = [x.split('_merged.mus.Aligned.out.sorted.CB.bam')[0] for x in df.columns]
    print("Reading counts for the cell_type: " + cell_type)
    print("The number of genes is: " + str(df.shape[0]))
    print("The number of cells is: " + str(df.shape[1]))
    return df

# Path: utils/functions.py