raw_dir: "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortex-mtg/data"
bam_files: "/gpfs/commons/groups/knowles_lab/Karin/Leaflet-analysis-WD/aligned/mini_allen_MTG"
results_dir: "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-cortex-mtg/Leaflet"
star_index_dir: "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-reference/star"
genome_fasta: "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-reference/gencode/GRCh38.primary_assembly.genome.fa"
gtf_file: "/gpfs/commons/datasets/controlled/BRAIN_NeMO/human-reference/gencode/gencode.v45.primary_assembly.annotation.gtf"
regtools_path: "/gpfs/commons/home/kisaev/regtools/build/regtools"
