import os
import subprocess
import time

configfile: "config_mouse_brain_dev_2021.yaml"

def get_sample_ids():
    raw_dir = config["raw_dir"]
    sample_ids = []
    
    # Get list of all potential samples
    sample_list = [s for s in os.listdir(raw_dir) if s.startswith("SRR") and os.path.isdir(os.path.join(raw_dir, s))]
    total_samples = len(sample_list)
    
    print(f"Checking {total_samples} samples for valid FASTQ files...")
    
    start_time = time.time()

    for i, sample_id in enumerate(sample_list, start=1):
        full_path = os.path.join(raw_dir, sample_id)
        fastq1 = os.path.join(full_path, f"{sample_id}_1.fastq.gz")
        fastq2 = os.path.join(full_path, f"{sample_id}_2.fastq.gz")

        if os.path.exists(fastq1) and os.path.exists(fastq2):
            sample_ids.append(sample_id)

        # Print progress every 10 samples
        if i % 100 == 0 or i == total_samples:
            elapsed_time = time.time() - start_time
            avg_time_per_sample = elapsed_time / i
            estimated_time_remaining = avg_time_per_sample * (total_samples - i)
            
            print(f"Processed {i}/{total_samples} ({(i/total_samples)*100:.1f}%) - "
                  f"Estimated time left: {estimated_time_remaining/60:.2f} min")

    print(f"Found {len(sample_ids)} samples.")
    return sample_ids

# Extract sample IDs (without validation)
sample_ids = get_sample_ids()

rule all:
    input:
        expand(os.path.join(config["results_dir"], "{sample}_junctions.bed"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_barcodes.txt"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed"), sample=sample_ids)

# Rule to generate STAR index
rule generate_star_index:
    output:
        flag = touch(config["star_index_dir"] + "/index_complete.flag")
    params:
        genome_fasta = config["genome_fasta"],
        gtf_file = config["gtf_file"]
    shell:
        """
        STAR --runThreadN 4 \
             --runMode genomeGenerate \
             --genomeDir {output[0]} \
             --genomeFastaFiles {params.genome_fasta} \
             --sjdbGTFfile {params.gtf_file}
        """

# STAR Alignment
rule run_star:
    input:
        star_index = rules.generate_star_index.output.flag,
        fastq1=os.path.join(config["raw_dir"], "{sample}", "{sample}_1.fastq.gz"),
        fastq2=os.path.join(config["raw_dir"], "{sample}", "{sample}_2.fastq.gz")
    output:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam")
    params:
        star_index_dir=config['star_index_dir'],
        output_prefix=os.path.join(config["bam_files"], "{sample}/"),
        log=os.path.join(config["bam_files"], "{sample}", "run_star.log")  # Log file per sample
    shell:
        """
        echo "Checking FASTQ files for {wildcards.sample}..." > {params.log}

        # Check if both FASTQ files exist and are non-empty
        if [ ! -s {input.fastq1} ] || [ ! -s {input.fastq2} ]; then
            echo "Skipping {wildcards.sample}: FASTQ files are empty or missing" >> {params.log}
            exit 0  # Exit normally so Snakemake continues
        fi

        echo "Running STAR for {wildcards.sample}..." >> {params.log}

        STAR --genomeDir {params.star_index_dir} \
             --readFilesIn {input.fastq1} {input.fastq2} \
             --readFilesCommand zcat \
             --runMode alignReads \
             --outSAMattributes XS \
             --outSAMstrandField intronMotif \
             --limitBAMsortRAM 44006670219 \
             --outSAMtype BAM SortedByCoordinate \
             --runThreadN 4 \
             --twopassMode Basic \
             --outFileNamePrefix {params.output_prefix}
        """

rule add_cb_tag:
    input:
        bam=rules.run_star.output.bam
    output:
        bam_CB=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam")
    params:
        sample=lambda wildcards: wildcards.sample
    shell:
        """
        echo "Adding CB tag to BAM file: {input.bam}"
        samtools view -h {input.bam} | awk -v cb="{params.sample}" 'BEGIN {{OFS="\t"}} {{if ($1 ~ /^@/) print; else print $0 "\tCB:Z:" cb;}}' | samtools view -b - > {output.bam_CB}
        """

# Rule to index BAM file
rule index_bam:
    input:
        bam=rules.add_cb_tag.output.bam_CB
    output:
        bai=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam.bai")
    shell:
        """
        echo "Indexing BAM file: {input.bam}"
        samtools index {input.bam}
        """

rule extract_junctions:
    input:
        bam=rules.add_cb_tag.output.bam_CB,
        bai=rules.index_bam.output.bai
    output:
        juncs=os.path.join(config["results_dir"], "{sample}_junctions.bed"),
        barcodes=os.path.join(config["results_dir"], "{sample}_barcodes.txt"),
        juncswbarcodes=os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed")
    params:
        regtools_path=config["regtools_path"]
    shell:
        """
        echo "Extracting junctions with barcodes from BAM file: {input.bam}"
        {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} -o {output.juncs} -s XS -b {output.barcodes}
        paste --delimiters='\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}
        echo "Done extracting junctions with barcodes"
        """