import os
import glob

configfile: "config_human_iPSC.yaml"

def get_sample_ids():
    sample_ids = set()
    search_path = os.path.join(config["raw_dir"], "*.fastq.gz")  # Look for all .fastq.gz files
    sample_file_check = {}
    missing_samples = []

    # Gather sample files and check for pairs
    for filepath in glob.glob(search_path):
        filename = os.path.basename(filepath)
        parts = filename.split('_')
        sample_id = parts[0]
        read_direction = parts[1].replace('.fastq.gz', '')  # e.g., "1" or "2"
        
        # Initialize a set for each sample's read directions
        if sample_id not in sample_file_check:
            sample_file_check[sample_id] = set()
        sample_file_check[sample_id].add(read_direction)

    # Collect sample IDs with both "_1" and "_2" files
    for sample_id, reads in sample_file_check.items():
        if "1" in reads and "2" in reads:
            sample_ids.add(sample_id)
        else:
            missing_samples.append(sample_id)
            print(f"Warning: Sample {sample_id} is missing one of the paired files.")

    # Save missing samples to a file
    with open("missing_samples.txt", "w") as f:
        for sample_id in missing_samples:
            f.write(f"{sample_id}\n")

    return list(sample_ids)

# Call the function and store the unique sample IDs
sample_ids = get_sample_ids()

# Print debug information
print("raw_dir:", config["raw_dir"])
print(f"Number of samples with both files: {len(sample_ids)}")

rule all:
    input:
        expand(os.path.join(config["results_dir"], "{sample}_junctions.bed"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_barcodes.txt"), sample=sample_ids),
        expand(os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed"), sample=sample_ids)

# Rule to generate STAR index
rule generate_star_index:
    output:
        directory(config["star_index_dir"]),
        flag = touch(config["star_index_dir"] + "/index_complete.flag")
    params:
        genome_fasta = config["genome_fasta"],
        gtf_file = config["gtf_file"]
    shell:
        """
        star --runThreadN 4 \
             --runMode genomeGenerate \
             --genomeDir {output[0]} \
             --genomeFastaFiles {params.genome_fasta} \
             --sjdbGTFfile {params.gtf_file}
        """

rule run_star:
    input:
        fastq1=os.path.join(config["raw_dir"], "{sample}_1.fastq.gz"),
        fastq2=os.path.join(config["raw_dir"], "{sample}_2.fastq.gz")
    output:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam"),
    params:
        star_index_dir=config['star_index_dir'],
        output_prefix=os.path.join(config["bam_files"], "{sample}/")
    shell:
        """
        star --genomeDir {params.star_index_dir} \
             --readFilesIn {input.fastq1} {input.fastq2} \
             --readFilesCommand zcat \
             --runMode alignReads \
             --outSAMattributes XS \
             --outSAMstrandField intronMotif \
             --limitBAMsortRAM 44006670219 \
             --outSAMtype BAM SortedByCoordinate \
             --runThreadN 4 \
             --twopassMode Basic \
             --outFileNamePrefix {params.output_prefix}
        """

rule add_cb_tag:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam")
    output:
        bam_CB=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam")
    params:
        sample=lambda wildcards: wildcards.sample
    shell:
        """
        echo "Adding CB tag to BAM file: {input.bam}"
        samtools view -h {input.bam} | awk -v cb={params.sample} 'BEGIN {{OFS="\t"}} {{$NF = $NF"\tCB:Z:"cb; print}}' | samtools view -bS - > {output.bam_CB}
        """

# Rule to index BAM file
rule index_bam:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam")
    output:
        bai=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam.bai")
    shell:
        """
        echo "Indexing BAM file: {input.bam}"
        samtools index {input.bam}
        """

rule extract_junctions:
    input:
        bam=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam"),
        bai=os.path.join(config["bam_files"], "{sample}", "Aligned.sortedByCoord.out.bam.CB.bam.bai")
    output:
        juncs=os.path.join(config["results_dir"], "{sample}_junctions.bed"),
        barcodes=os.path.join(config["results_dir"], "{sample}_barcodes.txt"),
        juncswbarcodes=os.path.join(config["results_dir"], "{sample}_junctions_with_barcodes.bed")
    params:
        regtools_path=config["regtools_path"]
    shell:
        """
        echo "Extracting junctions with barcodes from BAM file: {input.bam}"
        {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} -o {output.juncs} -s XS -b {output.barcodes}
        paste --delimiters='\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}
        echo "Done extracting junctions with barcodes"
        """