import os
import glob

configfile: "config_tabula_senis_3MO.yaml"

# Function to map sample IDs to their BAM file paths
def get_sample_ids():
    sample_bam_map = {}
    search_pattern = os.path.join(config["raw_dir"], "*", "results_gencode_ercc", "*.gencode.vM19.ERCC.Aligned.out.sorted.bam")
    for bam_file in glob.glob(search_pattern):
        sample_name = os.path.basename(bam_file).split(".")[0]
        sample_bam_map[sample_name] = bam_file
    return sample_bam_map

sample_bam_map = get_sample_ids()

rule all:
    input:
        expand("{results_dir}/{sample}/junctions_with_barcodes.bed",
               results_dir=config["results_dir"], sample=list(sample_bam_map.keys())),
        expand("{results_dir}/{sample}_splicing_summary.tsv",
               results_dir=config["results_dir"], sample=list(sample_bam_map.keys()))

# Rule to add CB tag to BAM files
rule add_cb_tag:
    input:
        bam = lambda wildcards: sample_bam_map[wildcards.sample]
    output:
        bam_CB = config["results_dir"] + "/{sample}/CB.bam"
    shell:
        """
        echo "Processing sample: {wildcards.sample}"
        echo "Expected BAM path: {input.bam}"

        if [[ ! -f "{input.bam}" ]]; then
            echo "ERROR: BAM file {input.bam} not found!"
            exit 1
        fi

        samtools view -h {input.bam} | awk -v cb="{wildcards.sample}" 'BEGIN {{OFS="\\t"}} {{if ($1 ~ /^@/) print; else print $0 "\\tCB:Z:" cb;}}' | samtools view -b - > {output.bam_CB}
        """

# Rule to index the BAM file
rule index_bam:
    input:
        bam = rules.add_cb_tag.output.bam_CB
    output:
        bai = config["results_dir"] + "/{sample}/CB.bam.bai"
    shell:
        """
        echo "Indexing BAM file: {input.bam}"
        samtools index {input.bam}
        """

# Rule to extract junctions with barcodes (without deleting the BAM file)
rule extract_junctions:
    input:
        bam = rules.add_cb_tag.output.bam_CB,
        bai = rules.index_bam.output.bai
    output:
        juncs = config["results_dir"] + "/{sample}/junctions.bed",
        barcodes = config["results_dir"] + "/{sample}/barcodes.txt",
        juncswbarcodes = config["results_dir"] + "/{sample}/junctions_with_barcodes.bed"
    params:
        regtools_path = config["regtools_path"]
    shell:
        """
        echo "Extracting junctions with barcodes from BAM file: {input.bam}"
        {params.regtools_path} junctions extract -a 6 -m 50 -M 500000 {input.bam} -o {output.juncs} -s XS -b {output.barcodes}

        # Combine junctions and barcodes
        paste --delimiters='\t' {output.juncs} {output.barcodes} > {output.juncswbarcodes}

        echo "Done extracting junctions with barcodes"
        """

# Rule to summarize splicing
rule summarize_splicing:
    input:
        bam = rules.add_cb_tag.output.bam_CB,
        juncs = config["results_dir"] + "/{sample}/junctions.bed"
    output:
        summary = config["results_dir"] + "/{sample}_splicing_summary.tsv"
    shell:
        """
        echo -e "Sample\tTotal_Reads\tSpliced_Reads\tUnspliced_Reads" > {output.summary}

        sample=$(basename {input.bam} | cut -d'.' -f1)
        total_reads=$(samtools view -c -F 4 {input.bam})

        # Ensure the file has at least five columns before extracting spliced reads
        spliced_reads=$(awk '{{if (NF >= 5) sum += $5}} END {{print (sum == "" ? 0 : sum)}}' "{input.juncs}")

        unspliced_reads=$((total_reads - spliced_reads))

        echo -e "$sample\t$total_reads\t$spliced_reads\t$unspliced_reads" >> {output.summary}
        echo "Splicing summary written to {output.summary}"
        """
